const audioFiles = [
    {name: 'button', src: 'audio/button.mp3'},
    {name: 'fightbg1', src: 'audio/fightbg1.mp3'},
    {name: 'battle_2_full', src: 'audio/battle_2_full.mp3'},
    {name: 'battle_2_half', src: 'audio/battle_2_half.mp3'},


    {name: 'emergency', src: 'audio/emergency.mp3'},
    {name: 'fizzle', src: 'audio/fizzle.mp3'},
    {name: 'matter_body', src: 'audio/matter_body.mp3'},
    {name: 'matter_enhance', src: 'audio/matter_enhance.mp3'},
    {name: 'matter_enhance_2', src: 'audio/matter_enhance_2.mp3'},
    {name: 'matter_shield', src: 'audio/matter_shield.mp3'},
    {name: 'matter_strike', src: 'audio/matter_strike.mp3'},
    {name: 'matter_strike_alt', src: 'audio/matter_strike_alt.mp3'},
    {name: 'matter_strike_hit', src: 'audio/matter_strike_hit.mp3'},
    {name: 'matter_strike_hit_alt', src: 'audio/matter_strike_hit_alt.mp3'},
    {name: 'matter_strike_hit_alt_2', src: 'audio/matter_strike_hit_alt_2.mp3'},
    {name: 'matter_strike_hit2', src: 'audio/matter_strike_hit2.mp3'},
    {name: 'matter_ultimate', src: 'audio/matter_ultimate.mp3'},

    {name: 'mind_strike', src: 'audio/mind_strike.mp3'},
    {name: 'mind_strike_hit', src: 'audio/mind_strike_hit.mp3'},
    {name: 'mind_enhance', src: 'audio/mind_enhance.mp3'},
    {name: 'mind_shield', src: 'audio/mind_shield.mp3'},
    {name: 'mind_shield_retaliate', src: 'audio/mind_shield_retaliate.mp3'},
    {name: 'mind_body', src: 'audio/mind_body.mp3'},
    {name: 'mind_ultimate_1', src: 'audio/mind_ultimate_1.mp3'},
    {name: 'mind_ultimate_2', src: 'audio/mind_ultimate_2.mp3'},
    {name: 'mind_ultimate_cast', src: 'audio/mind_ultimate_cast.mp3'},
    {name: 'mind_ultimate_loop_1', src: 'audio/mind_ultimate_loop_1.mp3'},
    {name: 'mind_ultimate_loop_2', src: 'audio/mind_ultimate_loop_2.mp3'},

    {name: 'tickslow', src: 'audio/tickslow.mp3'},
    {name: 'clocktick', src: 'audio/clocktick.mp3'},
    {name: 'time_body', src: 'audio/time_body.mp3'},
    {name: 'time_strike', src: 'audio/time_strike.mp3'},
    {name: 'time_strike_hit', src: 'audio/time_strike_hit.mp3'},
    {name: 'time_strike_hit_2', src: 'audio/time_strike_hit_2.mp3'},
    {name: 'time_enhance', src: 'audio/time_enhance.mp3'},
    {name: 'time_shield', src: 'audio/time_shield.mp3'},

    {name: 'void_strike', src: 'audio/void_strike.mp3'},
    {name: 'void_strike_hit', src: 'audio/void_strike_hit.mp3'},
    {name: 'void_body', src: 'audio/void_body.mp3'},
    {name: 'void_shield', src: 'audio/void_shield.mp3'},
    {name: 'void_ultimate', src: 'audio/void_ultimate.mp3'},
    {name: 'void_enhance', src: 'audio/void_enhance.mp3'},
    {name: 'meat_click_left', src: 'audio/meat_click_left.mp3'},
    {name: 'meat_click_right', src: 'audio/meat_click_right.mp3'},

    {name: 'victory', src: 'audio/victory.mp3'},
    {name: 'victory_2', src: 'audio/victory_2.mp3'},
    {name: 'victory_false', src: 'audio/victory_false.mp3'},

    {name: 'voca_gun', src: 'audio/voca_gun.mp3'},
    {name: 'voca_laser', src: 'audio/voca_laser.mp3'},
    {name: 'voca_claw_1', src: 'audio/voca_claw_1.mp3'},
    {name: 'voca_claw_2', src: 'audio/voca_claw_2.mp3'},
    {name: 'big_gun_pow_1', src: 'audio/big_gun_pow_1.mp3'},
    {name: 'big_gun_pow_2', src: 'audio/big_gun_pow_2.mp3'},

    {name: 'magic', src: 'audio/magic.mp3'},
    {name: 'power_surge', src: 'audio/power_surge.mp3'},
    {name: 'power_surge_plain', src: 'audio/power_surge_plain.mp3'},
    {name: 'tree_timber', src: 'audio/tree_timber.mp3'},
    {name: 'locket', src: 'audio/locket.mp3'},
    {name: 'razor_leaf', src: 'audio/razor_leaf.mp3'},
    {name: 'tree_hit', src: 'audio/tree_hit.mp3'},
    {name: 'clunk', src: 'audio/clunk.mp3'},
    {name: 'clunk2', src: 'audio/clunk2.mp3'},
    {name: 'cutesy_down', src: 'audio/cutesy_down.mp3'},
    {name: 'cutesy_up', src: 'audio/cutesy_up.mp3'},
    {name: 'goblin_aha', src: 'audio/goblin_aha.mp3'},
    {name: 'goblin_grunt', src: 'audio/goblin_grunt.mp3'},
    {name: 'enemy_attack', src: 'audio/enemy_attack.mp3'},
    {name: 'enemy_attack_2', src: 'audio/enemy_attack_2.mp3'},
    {name: 'enemy_attack_major', src: 'audio/enemy_attack_major.mp3'},
    {name: 'body_slam', src: 'audio/body_slam.mp3'},
    {name: 'punch', src: 'audio/punch.mp3'},
    {name: 'sword_slice', src: 'audio/sword_slice.mp3'},
    {name: 'sword_hit', src: 'audio/sword_hit.mp3'},
    {name: 'stone_wheel', src: 'audio/stone_wheel.mp3'},
    {name: 'stone_wheel_deep', src: 'audio/stone_wheel_deep.mp3'},
    {name: 'wind', src: 'audio/wind.mp3'},
    {name: 'sound_of_death', src: 'audio/sound_of_death.mp3'},
    {name: 'you_died', src: 'audio/you_died.mp3'},

    {name: 'magician_end', src: 'audio/magician_end.mp3'},
    {name: 'magician_theme_1', src: 'audio/magician_theme_1.mp3'},
    {name: 'magician_theme_3', src: 'audio/magician_theme_3.mp3'},
    {name: 'magician_theme_4', src: 'audio/magician_theme_4.mp3'},

    {name: 'shield_block', src: 'audio/shield_block.mp3'},
    {name: 'shield_break', src: 'audio/shield_break.mp3'},
    {name: 'rock_crumble', src: 'audio/rock_crumble.mp3'},

    {name: 'timeSlow', src: 'audio/timeslow.mp3'},
    {name: 'squish', src: 'audio/squish.mp3'},

]
