
let textData3 = {
    death2a: {en_us: '...OH? IT\'S YOU AGAIN.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death2b: {en_us: 'YOU DO NOT BELONG HERE,\nIN THE LANDS OF PASSING.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death2c: {en_us: 'TURN BACK TO WHERE\nYOU CAME FROM.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death3a: {en_us: 'I WILL ONLY\nWARN YOU ONCE MORE,',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death3b: {en_us: 'THAT WHICH YOU SEEK HERE\nCANNOT BE ATTAINED.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4a: {en_us: 'THE MAGICIAN THOUGHT HIS\nMAGIC COULD ELUDE ME,',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4b: {en_us: 'BUT THE PASSAGE OF TIME\nCANNOT BE UNDONE.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4c: {en_us: 'AND NEITHER CAN YOUR\nLOVED ONE RETURN.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death5a: {en_us: 'YOU MAY THINK YOURSELF A\nHERO, BUT UNDERSTAND THIS',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death5b: {en_us: 'NOTHING NOBLE CAN COME\nFROM THIS JOURNEY.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death6a: {en_us: "TRULY YOU ARE MAKING\nA MESS OF THINGS.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death6b: {en_us: "A MESS THAT I HAVE\nTO CLEAN UP.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7a: {en_us: "ALAS, IT IS NOT WITHIN\nMY AUTHORITY TO STOP YOU.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7b: {en_us: "BUT IF YOU WERE TO...\nENCOUNTER AN ACCIDENT,",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7c: {en_us: "THEN YOUR FATE WILL VERY\nMUCH BE IN MY HANDS.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death8a: {en_us: "...",
        fr: '...',
        zh_tw: '...',
        zh_cn: '...',
        ru: '...',
        es: '...',
        jp: '...'
    },
    death8b: {en_us: "I HAVE A FEELING THAT\nIT WON'T BE LONG",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death8c: {en_us: "BEFORE I HAVE BUSINESS WITH YOU.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
};

textData = { ...textData, ...textData3};
