let language = 'en_us';

const textData = {
    matter_strike_desc: {en_us: 'Deal 12 damage',
        fr: '',
        zh_cn: '造成 12 点伤害',
        ru: '',
        es: '',
        jp: ''
    },
    matter_strike_plus_desc: {en_us: 'Deal 14 damage',
        fr: '',
        zh_cn: '造成 14 点伤害',
        ru: '',
        es: '',
        jp: ''
    },
    matter_enhance_desc: {en_us: 'Next attack\nDeals +6\ndamage',
        fr: '',
        zh_cn: '下个攻击造成\n+6 点伤害',
        ru: '',
        es: '',
        jp: ''
    },
    matter_protect_desc: {en_us: 'Create a shield\nthat blocks 14\ndamage',
        fr: '',
        zh_cn: '创建一个阻挡\n14 点伤害的护盾',
        ru: '',
        es: '',
        jp: ''
    },
    matter_reinforce_desc: {en_us: 'When attacked,\nreduce damage\ntaken by 2 and\nreturn 2 damage',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    matter_unload_desc: {en_us: 'Deal 20 damage.\nBlock 20 damage\nfor the next\n5 seconds',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    time_strike_desc: {en_us: 'Deal 6 damage,\nthen deal half\nthat damage\na second time',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    time_enhance_desc: {en_us: 'Next attack\nis cast an\nextra time',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    time_protect_desc: {en_us: 'Create a shield\nthat delays up to\n50 damage',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    time_reinforce_desc: {en_us: 'Heal 50% of\nthe damage you\ntook from your\nlast injury',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    time_unload_desc: {en_us: 'Freeze time for\nthe next 6 spells.\nLoses power\nwith repeat use.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    void_strike_desc: {en_us: 'Damage 1.5%\nenemy current\nHP. Deal that\ndamage 2 more\ntimes after a\ndelay.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    void_enhance_desc: {en_us: 'Next attack\ncurses the enemy\nto take +1 damage\nfrom all sources',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    void_protect_desc: {en_us: 'Create a shield\nthat completely\nnegates one\nattack',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    void_reinforce_desc: {en_us: 'Heal to full, but\nat the cost of\n20% max hp',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    void_unload_desc: {en_us: 'Damage 12.5% of\nenemy current HP\nand disrupt their\naction',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    mind_strike_desc: {en_us: 'Deal 1 damage.\nEnemy takes x2\ndamage from\nnext attack hit',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    mind_enhance_desc: {en_us: 'Next attack deals\n3 DMG/s for\n4 seconds.\n(Non-stacking)',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    mind_enhance_plus_desc: {en_us: 'Next attack deals\n3 DMG/s for\n5 seconds',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    mind_protect_desc: {en_us: 'Create a shield\nthat reflects\nhalf the damage\nyou take',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    mind_reinforce_desc: {en_us: 'Attacks deal\n+2 damage',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    mind_unload_desc: {en_us: 'Next non-attack\nspell has +200%\neffectiveness',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    // ================== Tutorial ================
    // The Time rune grants
    // control of the temporal.
    matter_tut_desc: {en_us: 'The Matter rune grants\ncontrol of the physical.\nMatter spells are blunt and\ngood at dealing direct damage\nor providing reliable protection.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    matter_tut_strike_desc: {en_us: 'Conjure a ball of rock\nthat deals solid damage.\nSimple but effective.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    matter_tut_enhance_desc: {en_us: 'Makes your next attack\ndeal extra damage.\nAlso makes the attack a\nlittle bit bigger.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    matter_tut_protect_desc: {en_us: 'Creates a shield that blocks\na flat amount of damage.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    matter_tut_reinforce_desc: {en_us: 'Strengthen yourself with\nsharp spikes that both\nprotect you and inflict minor\ndamage back to your enemies.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    matter_tut_unload_desc: {en_us: 'Conjures a great deal of\nmatter to crush your enemies\nwhile keeping yourself safe.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    mind_tut_desc: {en_us: 'The Energy rune grants\ncontrol of raw energy.\nEnergy spells have powerful\nsupportive effects and can\ndeal damage that bypasses\nenemy shields.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    mind_tut_strike_desc: {en_us: 'Fires a bolt of energy that\ndeals little damage by itself,\nbut amplifies your next\nattack for double (x2) damage.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    mind_tut_enhance_desc: {en_us: 'Your next attack sets the\nenemy on fire, which deals\ndamage over time that\nbypasses shields.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    mind_tut_protect_desc: {en_us: 'Creates a shield that blocks\nhalf of all damage, while\nstoring up and retaliating with\nthe damage you do take.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    mind_tut_reinforce_desc: {en_us: 'Boosts your attacks to deal\nextra damage.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    mind_tut_ultimate_desc: {en_us: 'Multiplies the effectivness\nof your next non-attack\nspell.\nSupposedly it\'s possible to\ncast this spell twice in\na row for additional power.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},

    time_tut_desc: {en_us: 'The Time rune grants\ncontrol of the temporal.\nThis rune allows manipulation\nof time to multiply your attacks,\ndelay or rewind injuries,\nor even slow time to a standstill',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    time_tut_strike_desc: {en_us: 'An attack that strikes a second\ntime for +50% damage.\nParticularly strong with some\n+damage enhancements.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    time_tut_enhance_desc: {en_us: 'Your next attack is cast\nan extra time.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    time_tut_protect_desc: {en_us: 'Creates a shield that delays\nall damage you take to a\nslow trickle, but only up\nto a limit.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    time_tut_reinforce_desc: {en_us: 'Partially rewinds time to\nheal some of your recent\ninjuries.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    time_tut_ultimate_desc: {en_us: 'Freezes time for several\nspell casts.',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},


















    desc1: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc2: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc3: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc4: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc5: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc6: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc7: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc8: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc9: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},
    desc10: {en_us: '',
        fr: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''},


};

function setLanguage(lang) {
    language = lang;
}

function getLangText(textName) {
    if (!textData[textName]) {
        console.error("Missing text name ", textName);
        return "MISSING TEXT";
    }
    return textData[textName][language];
}
