
let textData2 = {
    encyclopedia_rune_element: {en_us: "Elemental Runes: ",
        fr: '',
        zh_tw: '元素符文：',
        zh_cn: '元素符文：',
        ru: '',
        es: '',
        jp: ''
    },
    encyclopedia_rune_action: {en_us: "Action Runes: ",
        fr: '',
        zh_tw: '行動符文：',
        zh_cn: '行动符文：',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_matter: {en_us: "Uses solid rock and stone for your spells",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_energy: {en_us: "Energy",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_energy: {en_us: "Uses raw energy to cast spells",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_time: {en_us: "Time",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_time: {en_us: "Manipulates time to cast spells",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_void: {en_us: "Void",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_void: {en_us: "Controls dark space to cast spells",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    encyc_enhance: {en_us: "Enhance",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_enhance: {en_us: "Strengthens your next attack",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_shield: {en_us: "Shield",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_shield: {en_us: "Creates shields to protect you",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_body: {en_us: "Body",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_body: {en_us: "Grants you various lasting effects",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_ultimate: {en_us: "Ultimate",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    encyc_desc_ultimate: {en_us: "Your most powerful spells",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    post_fight_title: {en_us: "Fight Complete",
        fr: '',
        zh_tw: '打架成功',
        zh_cn: '打架成功',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_health: {en_us: "Health Left: ",
        fr: '',
        zh_tw: '生命: ',
        zh_cn: '生命: ',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_newrune: {en_us: "New Rune!",
        fr: '',
        zh_tw: '新的符文！',
        zh_cn: '新的符文！',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_noupgrade: {en_us: "No Upgrade",
        fr: '',
        zh_tw: '没有升级',
        zh_cn: '沒有升級',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_upgrade: {en_us: "Upgraded!",
        fr: '',
        zh_tw: '升级!',
        zh_cn: '升級!',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_day: {en_us: "Day ",
        fr: '',
        zh_tw: '第 ',
        zh_cn: '第 ',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_day2: {en_us: "",
        fr: '',
        zh_tw: ' 天',
        zh_cn: ' 天',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story1: {en_us: "Here I stand in\nfront of the gates\nto the forbidden land\nof the departed.\n\n"+
            "Right away this place resists my entry.\n"+
            "But I know I will find you here dear Rosemary,\nand no creature or construct will stop me\nfrom reaching you.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story2: {en_us: "The fabled Reaper\nhas noticed me,\nthough I hardly feel afraid.\n\n" +
        "If anything, they remind me more of a\nnagging parent than some specter of\nthe underworld.\n\n"+
            "For now, I will rightfully claim this shield\nas my own.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story3: {en_us: "It seems I acquire\nthe strength of\neach foe I defeat!\n\n"+
            "The journey may be long, but perhaps\nif I triumph over enough foes, eventually\nI can even face Death itself!",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story4: {en_us: "My power grows\nwith each new foe\ndefeated.\n\nBut I must practice if I am to use them to\ntheir full potential.\n\n",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story5: {en_us: "I wonder about\nthe nature of the\ncreatures in this place.\n\n"+
            "Are they guardians and defenders?\nOr are they just unfortunate residents\nwho happen to be in my path?\n\n"+
            "Either way, I'll fight every last one if it\ngets me closer to you.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story6: {en_us: "Perhaps these\nobstacles are\nbeing set up by\nDeath to stop me!\n\n"+
        "But he ",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story7: {en_us: "The enemies I face\nare strong, but I\ngrow stronger still.\n\n"+
        "Maybe there is still room for improvement, but\nmy magic should be more than enough to\nrescue you, dearest Rosemary.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story8: {en_us: "Whether it's\nsoldiers or\bassassins, none can\nchallenge me.\n\n" +
            "Surely Death must be getting desperate\nknowing I am near my destination.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_story9: {en_us: "Not even the\nmachines of death\ncan best me!\n\n" +
            "I am at the peak of my\npower, and there is nothing left that\ncan stand in my way.\n\n" +
            "All I have to do now is get around this broken\nrobot and I know I will find her just around\nthe corner.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },


    post_fight_training: {en_us: "Training",
        fr: '',
        zh_tw: '練習',
        zh_cn: '练习',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_skip_training: {en_us: "SKIP TRAINING    ",
        fr: '',
        zh_tw: '跳過練習',
        zh_cn: '跳过练习',
        ru: '',
        es: '',
        jp: ''
    },
    post_fight_continue: {en_us: "CONTINUE         ",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    pre_fight_0a: {en_us: "CONTROLS:",
        fr: '',
        zh_tw: '控制：',
        zh_cn: '控制:',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0b: {en_us: "Click and drag\nthe wheels",
        fr: '',
        zh_tw: '點擊並拖曳\n' +
            '輪子',
        zh_cn: '点击并拖动\n' +
            '轮子',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0c: {en_us: "Strike",
        fr: '',
        zh_tw: '打擊符文',
        zh_cn: '打击符文',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0d: {en_us: "Matter",
        fr: '',
        zh_tw: '物質符文',
        zh_cn: '物质符文',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0e: {en_us: "Casts attack spells",
        fr: '',
        zh_tw: '施展攻擊法術',
        zh_cn: '施放攻击型法术',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0f: {en_us: "Uses solid rock and\nstone for your spells",
        fr: '',
        zh_tw: '使用岩石和\n' +
            '石头施展法术',
        zh_cn: '使用岩石和\n' +
            '石头施展法术',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0g: {en_us: "Deal 12 Damage",
        fr: '',
        zh_tw: '造成 12 點傷害',
        zh_cn: '造成 12 点伤害',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0h: {en_us: "Click to cast\nMatter+Strike\nspell",
        fr: '',
        zh_tw: '點擊投射\n' +
            '物質+打擊\n' +
            '法術',
        zh_cn: '点击投射\n' +
            '物质+打击\n' +
            '法术',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_1a: {en_us: "\"This is my shield, mine!\n Is family treasure from\n father's brother's aunt's\n grandpa's cousin's\n friend's neighbor!!\"",
        fr: '',
        zh_tw: '我終於到了。',
        zh_cn: '我终于到了。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_1b: {en_us: "There is no time to barter,\nand I must take every\nresource I can get if I am\nto rescue Rosemary.",
        fr: '',
        zh_tw: '在通往禁地的入口處。',
        zh_cn: '在通往禁地的门口。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_2a: {en_us: "I feel like this forest is watching me.",
        fr: '',
        zh_tw: '',
        zh_cn: '。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_2b: {en_us: "Surely it is only my imagination?",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_3a: {en_us: "A diminutive man laughs\nat me from his throne of\ntime-telling paraphernelia.",
        fr: '',
        zh_tw: '',
        zh_cn: '。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_3b: {en_us: "I challenge him and\nhe seems more than\nhappy to showcase his\ntemporal powers.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_4a: {en_us: 'In front of me stands a knight,\nmotionless but with sword drawn.',
        fr: '',
        zh_tw: '',
        zh_cn: '。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_4b: {en_us: "I accept the wordless challenge and\nface them head-on.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_5a: {en_us: 'No matter where I go, this wall\nalways seems to be blocking the way.',
        fr: '',
        zh_tw: '',
        zh_cn: '。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_5b: {en_us: "But if there is no entrance, then I\nwill simply make one.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    pre_fight_7a: {en_us: 'The sound of skittering legs cuts\nthrough the fog.',
        fr: '',
        zh_tw: '',
        zh_cn: '。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_7b: {en_us: "Something is hunting me.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_8a: {en_us: 'I sense something dangerous\bbarring the path up ahead.',
        fr: '',
        zh_tw: '',
        zh_cn: '。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_8b: {en_us: "But I'm certain I am ready\nfor anything.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_za: {en_us: "I've finally arrived.",
        fr: '',
        zh_tw: '我終於到了。',
        zh_cn: '我终于到了。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_zb: {en_us: "I doubt the goblin's claim\nof ownership",
        fr: '',
        zh_tw: '在通往禁地的入口處。',
        zh_cn: '在通往禁地的门口。',
        ru: '',
        es: '',
        jp: ''
    },

    level0_diag_a: {en_us: "This thing is in the way.",
        fr: '',
        zh_tw: '這東西擋住了我的路。',
        zh_cn: '这东西挡住了我的路。',
        ru: '',
        es: '',
        jp: ''
    },
    level0_diag_b: {en_us: "I should knock it over.",
        fr: '',
        zh_tw: '我應該把它打翻。',
        zh_cn: '我应该把它打翻。',
        ru: '',
        es: '',
        jp: ''
    },
    level0_tut_a: {en_us: "Spin the wheels to\n swap in fresh Runes ",
        fr: '',
        zh_tw: '旋轉輪子交換新的魔法符文',
        zh_cn: '旋转轮子来换取\n新的魔法符文',
        ru: '',
        es: '',
        jp: ''
    },
    level0_tut_b: {en_us: "Defeat the =>\nenemy to win",
        fr: '',
        zh_tw: '擊敗敵人獲勝 =>',
        zh_cn: '击败敌人获胜 =>',
        ru: '',
        es: '',
        jp: ''
    },
    level1_diag_a: {en_us: "Another obstacle?",
        fr: '',
        zh_tw: '怎麼出現另一個？',
        zh_cn: '怎么出现另一个？',
        ru: '',
        es: '',
        jp: ''
    },
    level1_diag_b: {en_us: "I should try my\nmore advanced spells.",
        fr: '',
        zh_tw: '我應該使用更\n高級的法術。',
        zh_cn: '我应该使用更\n高级的法术。',
        ru: '',
        es: '',
        jp: ''
    },
    level1_tut_a: {en_us: "The Enhance Rune\nstrengthens your\nnext attack\n ",
        fr: '',
        zh_tw: '增强符文\n增强你的下\n一次攻击\n ',
        zh_cn: '增强符文\n增强你的下\n一次攻击\n ',
        ru: '',
        es: '',
        jp: ''
    },
    level1_tut_b: {en_us: "Enemies get\nangry when\nattacked!",
        fr: '',
        zh_tw: '敵人受到攻擊時\n會生氣！',
        zh_cn: '敌人受到攻击时\n会愤怒！',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_diag_a: {en_us: "This new Rune I acquired\ncould be useful.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_diag_b: {en_us: "I should carefully consider\nwhat order I use my spells in.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_diag_c: {en_us: "I can do more damage if I\ninterweave different attacks.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_tut_a: {en_us: "Goal: Defeat the\nenemy in just\n4 spells",
        fr: '',
        zh_tw: '目標：僅用 4 個\b法術擊敗敵人',
        zh_cn: '目标：仅用 4 个\n法术击败敌人',
        ru: '',
        es: '',
        jp: ''
    },
    level2_tut_a: {en_us: "Some shields\nare more useful\nagainst certain\nattacks",
        fr: '',
        zh_tw: '有些盾牌在\n抵禦某些攻\n擊時更有用',
        zh_cn: '有些盾牌在\n抵御某些攻\n击时更有用',
        ru: '',
        es: '',
        jp: ''
    },
    level2_train_tut_a: {en_us: "Goal: Survive the\nenemy's attacks",
        fr: '',
        zh_tw: '目標：抵擋敵人\n的攻擊',
        zh_cn: '目标：抵挡敌人\n的进攻',
        ru: '',
        es: '',
        jp: ''
    },

    level4_train_tut_a: {en_us: "Goal: Defeat\nthe enemy",
        fr: '',
        zh_tw: '目標：擊敗敵人',
        zh_cn: '目标：击败敌人',
        ru: '',
        es: '',
        jp: ''
    },
    level4_train_tut_b: {en_us: "Heal your last\ninjury with\n          +",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level5_train_tut_a: {en_us: "Goal: Defeat\nthe dummy",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level5_train_tut_b: {en_us: "Fully heal\nyourself with\n          +",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level5_train_tut_c: {en_us: "Void shields can\nfully block single\npowerful attacks\n             +",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    level7_diag_a: {en_us: "Strange, I don't remember\nsetting up a training dummy here.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    dummy_mind_tut: {en_us: 'Energy Strike\nmakes your\nnext attack hit\ntwice as hard.\n            +',
        fr: '',
        zh_tw: '',
        zh_cn: '造成 12 点伤害',
        ru: '',
        es: '',
        jp: ''
    },

    new_game: {en_us: 'NEW GAME',
        fr: '',
        zh_tw: '新遊戲',
        zh_cn: '新游戏',
        ru: '',
        es: '',
        jp: ''
    },
    cont_game: {en_us: 'CONTINUE',
        fr: '',
        zh_tw: '繼續遊戲',
        zh_cn: '继续游戏',
        ru: '',
        es: '',
        jp: ''
    },
    cont_ui: {en_us: 'CONTINUE',
        fr: '',
        zh_tw: '繼續',
        zh_cn: '继续',
        ru: '',
        es: '',
        jp: ''
    },
};

textData = { ...textData, ...textData2};
