
let textData3 = {
    death2a: {en_us: '...OH? IT\'S YOU AGAIN.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death2b: {en_us: 'YOU DO NOT BELONG HERE,\nIN THE LANDS OF PASSING.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death2c: {en_us: 'TURN BACK TO WHERE\nYOU CAME FROM.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death3a: {en_us: 'I WILL ONLY\nWARN YOU ONCE MORE,',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death3b: {en_us: 'THAT WHICH YOU SEEK HERE\nCANNOT BE ATTAINED.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4a: {en_us: 'THE MAGICIAN THOUGHT HIS\nMAGIC COULD ELUDE ME,',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4b: {en_us: 'BUT THE PASSAGE OF TIME\nCANNOT BE UNDONE.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4c: {en_us: 'AND NEITHER CAN YOUR\nLOVED ONE RETURN.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death5a: {en_us: 'YOU MAY THINK YOURSELF A\nHERO, BUT UNDERSTAND THIS',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death5b: {en_us: 'NOTHING NOBLE CAN COME\nFROM THIS JOURNEY.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death6a: {en_us: "YOU ARE TRULY MAKING\nA MESS OF THINGS.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death6b: {en_us: "A MESS THAT I HAVE\nTO CLEAN UP.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7a: {en_us: "ALAS, IT IS NOT WITHIN\nMY AUTHORITY TO STOP YOU.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7b: {en_us: "BUT IF YOU WERE TO...\nENCOUNTER AN ACCIDENT,",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7c: {en_us: "THEN YOUR FATE WILL VERY\nMUCH BE IN MY HANDS.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death8a: {en_us: "...",
        fr: '...',
        zh_tw: '...',
        zh_cn: '...',
        ru: '...',
        es: '...',
        jp: '...'
    },
    death8b: {en_us: "I HAVE A FEELING THAT\nIT WON'T BE LONG",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death8c: {en_us: "BEFORE I HAVE BUSINESS WITH YOU.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    deathFight1a: {en_us: "THUS COMES THE END.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1b: {en_us: "UNFORTUNATE, BUT YOUR JOURNEY\nWAS NEVER MEANT TO BE.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1c: {en_us: "FAREWELL",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1d: {en_us: "SEEMS YOU'VE LEARNED\nA TRICK OR TWO.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1e: {en_us: "BUT CAN YOU SURVIVE DEATH\nBY A THOUSAND CUTS?",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1f: {en_us: "STILL ALIVE?",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1g: {en_us: "NO MORE MESSING AROUND",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    epilogue1a: {en_us: "ALAS, YOUR WOUNDS\nWERE TOO MANY TO BEAR.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1b: {en_us: "BUT FOR YOUR EFFORTS, I SHALL\nAT LEAST GRANT YOUR WISH...",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1c: {en_us: "TO BE BESIDE YOUR BELOVED.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1d: {en_us: "MAY YOU FIND PEACE\nIN ETERNAL SLUMBER.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1e: {en_us: "Ending 1\nEternal Rest",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    epilogue2a: {en_us: "I SEE YOUR DESIRE TO\nSEEK VICTORY REMAINS INSATIABLE.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2b: {en_us: "SHOULD I WISH, IT WOULD BE\nTRIVIAL TO SIMPLY...",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2c: {en_us: "END YOUR LIFE BY FORCE.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2d: {en_us: "BUT YOU DO NOT DESERVE\nSUCH MERCY.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2e: {en_us: "I WILL GIVE YOU BACK\nYOUR BELOVED",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2f: {en_us: "AND YOU SHALL WANDER THE\nWORLD ETERNALLY WITHOUT REST.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },


};

textData = { ...textData, ...textData3};
