
let textData2 = {
    pre_fight_0z: {en_us: "I can only hope this is\nenough to rescue my beloved.",
        fr: '',
        zh_tw: '我終於到了。',
        zh_cn: '我终于到了。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0a: {en_us: "CONTROLS:",
        fr: '',
        zh_tw: '我終於到了。',
        zh_cn: '我终于到了。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0b: {en_us: "Click and drag\nthe wheels",
        fr: '',
        zh_tw: '在通往禁地的入口處。',
        zh_cn: '在通往禁地的门口。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0c: {en_us: "Strike Rune",
        fr: '',
        zh_tw: '我知道我會在這裡找到你，我親愛的。',
        zh_cn: '我知道我会在这里找到你，我亲爱的。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0d: {en_us: "Matter Rune",
        fr: '',
        zh_tw: '我知道我會在這裡找到你，我親愛的。',
        zh_cn: '我知道我会在这里找到你，我亲爱的。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0e: {en_us: "Casts attack spells",
        fr: '',
        zh_tw: '我知道我會在這裡找到你，我親愛的。',
        zh_cn: '我知道我会在这里找到你，我亲爱的。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0f: {en_us: "Uses solid rock and\nstone for your spells",
        fr: '',
        zh_tw: '我知道我會在這裡找到你，我親愛的。',
        zh_cn: '我知道我会在这里找到你，我亲爱的。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0g: {en_us: "Line up two runes\nto select a spell",
        fr: '',
        zh_tw: '我知道我會在這裡找到你，我親愛的。',
        zh_cn: '我知道我会在这里找到你，我亲爱的。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_0h: {en_us: "Click\nto cast\nspell",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_1a: {en_us: "\"This is my shield, mine!\n Is family treasure from\n father's brother's aunt's\n grandpa's cousin's\n friend's neighbor!!\"",
        fr: '',
        zh_tw: '我終於到了。',
        zh_cn: '我终于到了。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_1b: {en_us: "I doubt this dirty creature\ncould legitimately own\nsomething so valuable, so\nI'll take the prized shield\nfor myself.",
        fr: '',
        zh_tw: '在通往禁地的入口處。',
        zh_cn: '在通往禁地的门口。',
        ru: '',
        es: '',
        jp: ''
    },

    pre_fight_za: {en_us: "I've finally arrived.",
        fr: '',
        zh_tw: '我終於到了。',
        zh_cn: '我终于到了。',
        ru: '',
        es: '',
        jp: ''
    },
    pre_fight_zb: {en_us: "I doubt the goblin's claim\nof ownership",
        fr: '',
        zh_tw: '在通往禁地的入口處。',
        zh_cn: '在通往禁地的门口。',
        ru: '',
        es: '',
        jp: ''
    },

    level0_diag_a: {en_us: "This thing is in the way.",
        fr: '',
        zh_tw: '這東西擋住了我的路。',
        zh_cn: '这东西挡住了我的路。',
        ru: '',
        es: '',
        jp: ''
    },
    level0_diag_b: {en_us: "I should knock it over.",
        fr: '',
        zh_tw: '我應該把它打翻。',
        zh_cn: '我应该把它打翻。',
        ru: '',
        es: '',
        jp: ''
    },
    level0_tut_a: {en_us: "Spin the wheels to\n swap in fresh Runes ",
        fr: '',
        zh_tw: '旋轉輪子交換新的魔法符文',
        zh_cn: '旋转轮子来换取\n新的魔法符文',
        ru: '',
        es: '',
        jp: ''
    },
    level0_tut_b: {en_us: "Defeat the =>\nenemy to win",
        fr: '',
        zh_tw: '擊敗敵人獲勝 =>',
        zh_cn: '击败敌人获胜 =>',
        ru: '',
        es: '',
        jp: ''
    },
    level1_diag_a: {en_us: "Another obstacle?",
        fr: '',
        zh_tw: '怎麼出現另一個？',
        zh_cn: '怎么出现另一个？',
        ru: '',
        es: '',
        jp: ''
    },
    level1_diag_b: {en_us: "I should try my\nmore advanced spells.",
        fr: '',
        zh_tw: '我應該使用更\n高級的法術。',
        zh_cn: '我应该使用更\n高级的法术。',
        ru: '',
        es: '',
        jp: ''
    },
    level1_tut_a: {en_us: "The Enhance Rune\nstrengthens your\nnext attack\n ",
        fr: '',
        zh_tw: '增强符文\n增强你的下\n一次攻击\n ',
        zh_cn: '增强符文\n增强你的下\n一次攻击\n ',
        ru: '',
        es: '',
        jp: ''
    },
    level1_tut_b: {en_us: "Enemies get\nangry when\nattacked!",
        fr: '',
        zh_tw: '敵人受到攻擊時\n會生氣！',
        zh_cn: '敌人受到攻击时\n会愤怒！',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_diag_a: {en_us: "This new Rune I acquired\ncould be useful.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_diag_b: {en_us: "I should be more strategic\nwith my spells.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_diag_c: {en_us: "I should carefully consider\nwhat order I use my spells in.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level1_train_tut_a: {en_us: "Goal: Defeat the\ndummy in just\n4 spells.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level2_train_tut_a: {en_us: "Goal: Survive the\ndummy's attacks.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    level4_train_tut_a: {en_us: "Goal: Defeat\nthe dummy",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level4_train_tut_b: {en_us: "Heal your last\ninjury with\n          +",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level5_train_tut_a: {en_us: "Goal: Defeat\nthe dummy",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level5_train_tut_b: {en_us: "Fully heal\nyourself with\n          +",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    level5_train_tut_c: {en_us: "Void shields can\nfully block single\npowerful attacks\n             +",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    level1_diag: {

    },


    dummy_mind_tut: {en_us: 'Energy Strike\nmakes your\nnext attack hit\ntwice as hard.\n            +',
        fr: '',
        zh_tw: '',
        zh_cn: '造成 12 点伤害',
        ru: '',
        es: '',
        jp: ''
    },

    new_game: {en_us: 'NEW GAME',
        fr: '',
        zh_tw: '新遊戲',
        zh_cn: '新游戏',
        ru: '',
        es: '',
        jp: ''
    },
    cont_game: {en_us: 'CONTINUE',
        fr: '',
        zh_tw: '繼續遊戲',
        zh_cn: '继续游戏',
        ru: '',
        es: '',
        jp: ''
    },
    cont_ui: {en_us: 'CONTINUE',
        fr: '',
        zh_tw: '繼續',
        zh_cn: '继续',
        ru: '',
        es: '',
        jp: ''
    },
};

textData = { ...textData, ...textData2};
