
let textData3 = {
    beginLocket1: {en_us: "I'll reach you soon,\nmy beloved...",
        fr: '',
        zh_tw: '',
        zh_cn: '...哦？又是你。',
        ru: '',
        es: '',
        jp: ''
    },
    death2a: {en_us: '...OH? IT\'S YOU AGAIN.',
        fr: '',
        zh_tw: '',
        zh_cn: '...哦？又是你。',
        ru: '',
        es: '',
        jp: ''
    },
    death2b: {en_us: 'YOU DO NOT BELONG HERE,\nIN THE LANDS OF PASSING.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death2c: {en_us: 'TURN BACK TO WHERE\nYOU CAME FROM.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death3a: {en_us: 'I WILL ONLY\nWARN YOU ONCE MORE,',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death3b: {en_us: 'THAT WHICH YOU SEEK HERE\nCANNOT BE ATTAINED.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4a: {en_us: 'THE MAGICIAN THOUGHT HIS\nMAGIC COULD ELUDE ME,',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4b: {en_us: 'BUT THE PASSAGE OF TIME\nCANNOT BE UNDONE.',
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death4c: {en_us: "AND NEITHER CAN YOU RECLAIM\nWHAT YOU'VE LOST.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death5a: {en_us: 'YOU MAY THINK YOURSELF A\nHERO, BUT UNDERSTAND THIS',
        fr: '',
        zh_tw: '你也許認為自己是英雄，但要明白這一點',
        zh_cn: '你也许认为自己是英雄，但要明白这一点',
        ru: '',
        es: '',
        jp: ''
    },
    death5b: {en_us: 'NOTHING NOBLE CAN COME\nFROM THIS JOURNEY.',
        fr: '',
        zh_tw: '你的旅程不會帶來任何高貴的收穫。',
        zh_cn: '你的旅程不会带来任何高尚的收获。',
        ru: '',
        es: '',
        jp: ''
    },
    death6a: {en_us: "YOU ARE TRULY MAKING\nA MESS OF THINGS.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death6b: {en_us: "A MESS THAT I HAVE\nTO CLEAN UP.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7a: {en_us: "ALAS, IT IS NOT WITHIN\nMY AUTHORITY TO STOP YOU.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7b: {en_us: "BUT SHOULD YOU ENCOUNTER\nAN ACCIDENT,",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death7c: {en_us: "THEN YOUR FATE WILL BE\nENTIRELY IN MY HANDS.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death8a: {en_us: "...",
        fr: '...',
        zh_tw: '...',
        zh_cn: '...',
        ru: '...',
        es: '...',
        jp: '...'
    },
    death8b: {en_us: "I HAVE A FEELING THAT\nIT WON'T BE LONG",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    death8c: {en_us: "BEFORE I HAVE BUSINESS\nWITH YOU.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    deathFight1a: {en_us: "UNFORTUNATE, YOUR JOURNEY\nWAS NOT MEANT TO BE.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1b: {en_us: "FAREWELL",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1c: {en_us: "YOU'VE LEARNED SOME\nNEW TRICKS. NOT BAD.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1d: {en_us: "BUT YOU'LL NEED MORE\nTO AVOID YOUR FATE.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1e: {en_us: "DEATH BY A THOUSAND CUTS",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1f: {en_us: "STILL ALIVE?",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1g: {en_us: "NO MORE MESSING AROUND",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1h: {en_us: "...HMPH,\nSHODDY EQUIPMENT",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1i: {en_us: "SEEMS I HAVE TO BE\nMORE HANDS ON.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight1j: {en_us: "IT'S BEEN A LONG TIME SINCE\nI'VE HAD TO BE \"HANDS ON\".",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    deathFight2a: {en_us: "PREPARE YOURSELF!",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    deathFight2b: {en_us: "FAREWELL",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },


    epilogue1a: {en_us: "ALAS, YOUR WOUNDS\nWERE TOO MANY TO BEAR.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1b: {en_us: "BUT FOR YOUR EFFORTS, I SHALL\nAT LEAST GRANT YOUR WISH...",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1c: {en_us: "TO BE BESIDE YOUR BELOVED.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1d: {en_us: "MAY YOU FIND PEACE\nIN ETERNAL SLUMBER.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue1e: {en_us: "Ending 1\nEternal Rest",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },

    epilogue2a: {en_us: "I SEE YOUR DESIRE TO\nSEEK VICTORY REMAINS INSATIABLE.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2b: {en_us: "SHOULD I WISH, IT WOULD BE\nTRIVIAL TO SIMPLY...",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2c: {en_us: "END YOUR LIFE BY FORCE.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2d: {en_us: "BUT YOU DO NOT DESERVE\nSUCH MERCY.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2e: {en_us: "I WILL GIVE YOU BACK\nYOUR BELOVED",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },
    epilogue2f: {en_us: "AND YOU SHALL WANDER THE\nWORLD ETERNALLY WITHOUT REST.",
        fr: '',
        zh_tw: '',
        zh_cn: '',
        ru: '',
        es: '',
        jp: ''
    },


};

textData = { ...textData, ...textData3};
